### PR TITLE
Add dummy inhibitions

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
Towards: https://github.com/giantswarm/giantswarm/issues/25340

This PR adds dummy inhibition labels to allow the new CI to pass. 

### Checklist

- [x] Update CHANGELOG.md
- [ ] Add [Unit tests](https://github.com/giantswarm/prometheus-rules/#testing)
- [ ] Follow [Alert structure](https://github.com/giantswarm/prometheus-rules/#how-alerts-are-structured)
- [ ] Consider [creating a dashboard](https://docs.giantswarm.io/getting-started/observability/grafana/custom-dashboards/) ([guidelines](https://intranet.giantswarm.io/docs/product/ux/guidelines/dashboards/)) (if it does not exist already) to help oncallers monitor the status of the issue.
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

### CODE REVIEW

**Comment by QuantumEnigmaa** [comment]
It is using an older version of the test script. With the current version, we have this output : 
```
## Found 2 missing target labels
## Those labels should be defined by an alert in "prometheus-rules/templates/alerting-rules"
apiserver_down
scrape_timeout
exit status 1
```
cf https://github.com/giantswarm/prometheus-rules/pull/597

**Comment by hervenicol** [comment]
> It is using an older version of the test script. With the current version, we have this output :

Ouch, that makes it hard to review.
Yet, `exit status 1` means error, which we should note have anymore with the dummy inhibitions.

**Comment by QuantumEnigmaa** [comment]
>Yet, exit status 1 means error, which we should note have anymore with the dummy inhibitions.

This is due to the fact that these dummy labels are not merged on main yet so the checkLabel-failure branch don't have acces to it. Once this PR will be merged, the CI should pass.
I can test locally to be sure.

**Review by hervenicol — APPROVED** [review]
ok, then I trust you and your tests :sweat_smile:

**Pull request merged**
