### PR TITLE
handover VPA alert to turtle/phoenix

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: giantswarm/giantswarm#27172

Move all VPA related alerts ownership to team turtle and phoenix.

### CODE REVIEW

**Review by marieroque — APPROVED** [review]

**Comment by QuentinBisson** [comment]
I think you're missing thé webhook one

**Comment by TheoBrigitte** [comment]
> I think you're missing thé webhook one

Which one is that ?

**Comment by TheoBrigitte** [comment]
Alright I added `WorkloadClusterWebhookDurationExceedsTimeoutPhoenix` by splitting it from `WorkloadClusterWebhookDurationExceedsTimeoutAtlas`

**Comment by QuentinBisson** [comment]
Nice, sorry i was not on my laptop :)

**Comment by TheoBrigitte** [comment]
I would need a review from @giantswarm/team-turtles and/or @giantswarm/team-phoenix here please.

**Comment by fiunchinho** [comment]
When was this discussed? Was that recorded? I was interested in understanding the reasoning behind this. I was not aware phoenix was getting the VPA ownership.

**Comment by QuentinBisson** [comment]
@fiunchinho turtles is but they are sharing the rotation with you

**Comment by TheoBrigitte** [comment]
> When was this discussed? Was that recorded? I was interested in understanding the reasoning behind this. I was not aware phoenix was getting the VPA ownership.

This was discussed on August 10th with @giantswarm/team-turtles, but then held along with KSM in this other PR for no reason https://github.com/giantswarm/prometheus-rules/pull/889
VPA ownership is now in Turtle and so should be the alerts.

**Pull request merged**
