### PR TITLE
Add prometheus operator alerts

### PR DESCRIPTION
**Pull request by QuentinBisson**
Closes https://github.com/giantswarm/giantswarm/issues/15600

This PR:

- adds prometheus operator alerts from https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml
- depends on https://github.com/giantswarm/config/pull/309

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

### CODE REVIEW

**Comment by mig4** [comment]
Just wondering how noisy those alerts are. Did you run with this for any longer period of time on a test installation?

**Comment by QuentinBisson** [comment]
I will today as I'm oncall :) I set most of the alerts as notify alerts anyway :D

**Comment by QuentinBisson** [comment]
Nothing happening on Gauss since this morning:
image

**Review by mig4 — APPROVED** [review]

**Comment by QuentinBisson** [comment]
@mig4 can you review the config PR linked in the description as well ?

**Comment by QuentinBisson** [comment]
Theo did already :)

**Pull request merged**
