### PR TITLE
Fix incorrect ksm alert fixing on mimir

### PR DESCRIPTION
**Pull request by QuentinBisson**
Before adding a new alerting rule into this repository you should consider creating an SLO rules instead.
SLO helps you both increase the quality of your monitoring and reduce the alert noise.

* How to create a SLO rule: https://github.com/giantswarm/sloth-rules#how-to-create-a-slo
* Documentation: https://intranet.giantswarm.io/docs/monitoring/slo-alerting/

---
This PR fixes the ongoing ksm alerts on grizzly, caused by some leftover slos (data being kept for 30 days, the initial query was counting them so firing for the wrong reasons).

Adding the regex of __name__ ensures we only count the ksm generated alerts in the query.

### Checklist

- [x] Update CHANGELOG.md
- [ ] Add [Unit tests](https://github.com/giantswarm/prometheus-rules/#testing)
- [ ] Follow [Alert structure](https://github.com/giantswarm/prometheus-rules/#how-alerts-are-structured)
- [ ] Consider [creating a dashboard](https://docs.giantswarm.io/getting-started/observability/grafana/custom-dashboards/) ([guidelines](https://intranet.giantswarm.io/docs/product/ux/guidelines/dashboards/)) (if it does not exist already) to help oncallers monitor the status of the issue.
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

### CODE REVIEW

**Review by QuantumEnigmaa — APPROVED** [review]

**Comment by hervenicol** [comment]
Can't we limit the query to more recent data? Because if it takes old data into account, it won't work as expected (ie alerting when there's no recent data from KSM)?

**Comment by QuentinBisson** [comment]
It does not take old data into account as it's using a count

**Comment by hervenicol** [comment]
oh, it's SLO-generated data, but not old data!
image

**Comment by QuentinBisson** [comment]
Yes that's what I explained by:

```
caused by some leftover slos (data being kept for 30 days, the initial query was counting them so firing for the wrong reasons).
```

**Comment by hervenicol** [comment]
Yes, but when I read "data being kept for 30 days" I understand "old data" :sweat_smile: 
So the new query looks like this, which looks good :+1:  
image

**Review by hervenicol — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Good to know how I can improve :)

**Pull request merged**
