### PR TITLE
Unit tests: filter files to test

### PR DESCRIPTION
**Pull request by hervenicol**
This PR adds a feature to the unit tests:
we can now filter which files we want to test.

Allows faster iteration when writing a unit test.

### How it works:

* with a word:
```
$ make test test_filter=grafana
./test/hack/bin/fetch-tools.sh
bash test/hack/bin/verify-rules.sh "grafana"
21:21:30 promtool: start
### Helm chart preparation
2022/11/29 21:21:30 templating helm chart
dir: /home/herve/github/giantswarm/prometheus-rules/helm/prometheus-rules
sha: 0a10680da4981651be16a504fa7228e5a8c04d0d
tag: 
app-version: 2.62.1-0a10680da4981651be16a504fa7228e5a8c04d0d
version: 2.62.1-0a10680da4981651be16a504fa7228e5a8c04d0d
2022/11/29 21:21:30 templated helm chart
### Running tests for provider: openstack
###  Testing templates/alerting-rules/grafana.management-cluster.rules.yml
###    extracting /home/herve/github/giantswarm/prometheus-rules/test/providers/openstack/grafana.management-cluster.rules.yml
###    promtool check rules /home/herve/github/giantswarm/prometheus-rules/test/tests/providers/openstack/grafana.management-cluster.rules.yml
###    promtool test rules grafana.management-cluster.rules.test.yml - global
21:21:31 promtool: end (Elapsed time: 1s)

Congratulations!  Prometheus rules have been promtool checked and tested
```

* with a regex:
```
[prometheus-rules]$ make test test_filter=gr.*na
./test/hack/bin/fetch-tools.sh
bash test/hack/bin/verify-rules.sh "gr.*na"
21:22:30 promtool: start
### Helm chart preparation
2022/11/29 21:22:30 templating helm chart
dir: /home/herve/github/giantswarm/prometheus-rules/helm/prometheus-rules
sha: 0a10680da4981651be16a504fa7228e5a8c04d0d
tag: 
app-version: 2.62.1-0a10680da4981651be16a504fa7228e5a8c04d0d
version: 2.62.1-0a10680da4981651be16a504fa7228e5a8c04d0d
2022/11/29 21:22:30 templated helm chart
### Running tests for provider: openstack
###  Testing templates/alerting-rules/grafana.management-cluster.rules.yml
###    extracting /home/herve/github/giantswarm/prometheus-rules/test/providers/openstack/grafana.management-cluster.rules.yml
###    promtool check rules /home/herve/github/giantswarm/prometheus-rules/test/tests/providers/openstack/grafana.management-cluster.rules.yml
###    promtool test rules grafana.management-cluster.rules.test.yml - global
21:22:31 promtool: end (Elapsed time: 1s)

Congratulations!  Prometheus rules have been promtool checked and tested
```

* with no parameter:
```
[prometheus-rules]$ make test                   
./test/hack/bin/fetch-tools.sh
bash test/hack/bin/verify-rules.sh ""
21:19:12 promtool: start
### Helm chart preparation
2022/11/29 21:19:12 templating helm chart
dir: /home/herve/github/giantswarm/prometheus-rules/helm/prometheus-rules
sha: 0a10680da4981651be16a504fa7228e5a8c04d0d
tag: 
app-version: 2.62.1-0a10680da4981651be16a504fa7228e5a8c04d0d
version: 2.62.1-0a10680da4981651be16a504fa7228e5a8c04d0d
2022/11/29 21:19:12 templated helm chart
### Running tests for provider: openstack
###  Testing templates/alerting-rules/alertmanager-dashboard.rules.yml
###    extracting /home/herve/github/giantswarm/prometheus-rules/test/providers/openstack/alertmanager-dashboard.rules.yml
Error: could not find template templates/alerting-rules/alertmanager-dashboard.rules.yml in chart
###    Failed extracting rules file templates/alerting-rules/alertmanager-dashboard.rules.yml
###  Testing templates/alerting-rules/alertmanager.rules.yml
###    extracting /home/herve/github/giantswarm/prometheus-rules/test/providers/openstack/alertmanager.rules.yml
###    promtool check rules /home/herve/github/giantswarm/prometheus-rules/test/tests/providers/openstack/alertmanager.rules.yml
###    Skipping templates/alerting-rules/alertmanager.rules.yml: listed in test/conf/promtool_ignore
###  Testing templates/alerting-rules/apiserver.management-cluster.rules.yml
###    extracting /home/herve/github/giantswarm/prometheus-rules/test/providers/openstack/apiserver.management-cluster.rules.yml
###    promtool check rules /home/herve/github/giantswarm/prometheus-rules/test/tests/providers/openstack/apiserver.management-cluster.rules.yml
###    Skipping templates/alerting-rules/apiserver.management-cluster.rules.yml: listed in test/conf/promtool_ignore
[...]
```

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [ ] Add Unit tests
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).
- [ ] Alerting rules must have a comment documenting why it needs to exist.
- [ ] Consider creating a dashboard (if it does not exist already) to help oncallers monitor the status of the issue.

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Can we also make test 1 file only?

**Comment by hervenicol** [comment]
> Can we also make test 1 file only?

I'm not sure I understand your question.
You can set a filter that only matches one file, just like it does in the examples.
You can also have the filter more specific, like that:

```
[prometheus-rules]$ make test test_filter=grafana.management-cluster.rules.yml
./test/hack/bin/fetch-tools.sh
bash test/hack/bin/verify-rules.sh "grafana.management-cluster.rules.yml"
22:28:09 promtool: start
### Helm chart preparation
2022/11/29 22:28:09 templating helm chart
dir: /home/herve/github/giantswarm/prometheus-rules/helm/prometheus-rules
sha: 0a10680da4981651be16a504fa7228e5a8c04d0d
tag: 
app-version: 2.62.1-0a10680da4981651be16a504fa7228e5a8c04d0d
version: 2.62.1-0a10680da4981651be16a504fa7228e5a8c04d0d
2022/11/29 22:28:09 templated helm chart
### Running tests for provider: openstack
###  Testing templates/alerting-rules/grafana.management-cluster.rules.yml
###    extracting /home/herve/github/giantswarm/prometheus-rules/test/providers/openstack/grafana.management-cluster.rules.yml
###    promtool check rules /home/herve/github/giantswarm/prometheus-rules/test/tests/providers/openstack/grafana.management-cluster.rules.yml
###    promtool test rules grafana.management-cluster.rules.test.yml - global
22:28:10 promtool: end (Elapsed time: 1s)

Congratulations!  Prometheus rules have been promtool checked and tested
```

**Comment by QuentinBisson** [comment]
Sorry, it was too late for me to review :grin: 

Can you add an example on how to test one singular file as I think this will be the most common use case

**Comment by hervenicol** [comment]
> Can you add an example on how to test one singular file as I think this will be the most common use case

Done! Do you like it better now @QuentinBisson ?

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
This is purrfect

**Pull request merged**
