### PR TITLE
Fix all kubenetes mixins according to pint

### PR DESCRIPTION
**Pull request by QuentinBisson**
Before adding a new alerting rule into this repository you should consider creating an SLO rules instead.
SLO helps you both increase the quality of your monitoring and reduce the alert noise.

* How to create a SLO rule: https://github.com/giantswarm/sloth-rules#how-to-create-a-slo
* Documentation: https://intranet.giantswarm.io/docs/monitoring/slo-alerting/

---
Towards: https://github.com/giantswarm/...

This PR fixes mixins according to basic pint recommendations

### Checklist

- [x] Update CHANGELOG.md
- [ ] Add [Unit tests](https://github.com/giantswarm/prometheus-rules/#testing)
- [ ] Follow [Alert structure](https://github.com/giantswarm/prometheus-rules/#how-alerts-are-structured)
- [ ] Consider [creating a dashboard](https://docs.giantswarm.io/getting-started/observability/grafana/custom-dashboards/) ([guidelines](https://intranet.giantswarm.io/docs/product/ux/guidelines/dashboards/)) (if it does not exist already) to help oncallers monitor the status of the issue.
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

### CODE REVIEW

**Comment by hervenicol** [comment]
Have upstream mixins been updated accordingly? So next time we upgrade we don't have to re-apply all these changes?

**Comment by QuentinBisson** [comment]
Which ones ? The Kubernetes ones most likely not. Thé Loki and Mimir ones nope but that's s in other PRs and it's sadly not ready yet anyway

**Comment by QuentinBisson** [comment]
The kubernetes mixin script was updated but for loki and mimir it's currently not merged

**Comment by QuentinBisson** [comment]
See https://github.com/giantswarm/prometheus-rules/pull/1131

**Comment by QuentinBisson** [comment]
@hervenicol I fixed the upgrade script to add the labels using sed https://github.com/giantswarm/giantswarm/issues/30310

**Review by QuantumEnigmaa — APPROVED** [review]
LGTM

**Review by marieroque — COMMENTED** [review]
LGTM

**Review by marieroque — APPROVED** [review]

**Pull request merged**
