### PR TITLE
fix: ownership - change honeybadger to cabbage

### PR DESCRIPTION
**Pull request by piontec**
This PR:

- fixes ownership of kong*, cert-manager* and external-dns* to team-cabbage, according to [this spreadsheet](https://docs.google.com/spreadsheets/d/1GNXAbYo_HyjjRusd2KTGttuORBkX9iMdgnNp-xTQ9sw/edit#gid=0)

### CODE REVIEW

**Review by mproffitt — APPROVED** [review]

**Comment by Gacko** [comment]
Just a heads up: `cert-manager` moved to @giantswarm/team-hydra recently, but I totally get this is not the scope of your PR. :)

**Comment by piontec** [comment]
> Just a heads up: `cert-manager` moved to @giantswarm/team-hydra recently, but I totally get this is not the scope of your PR. :)
But if it did, let's make it right and move it there.

**Comment by Gacko** [comment]
Just a minor markdown question: Do we need to escape the asterisks? Because I feel like the changelog will end up "formatted" with the wildcards

**Comment by nprokopic** [comment]
> Just a heads up: `cert-manager` moved to @giantswarm/team-hydra recently, but I totally get this is not the scope of your PR. :)

Not that I'm a fan of Hydra getting `cert-manager` ownership, but yeah, expression here includes `cert-manager`:

```
expr: managed_app_deployment_status_replicas_unavailable{cluster_type="workload_cluster", managed_app=~"cert-manager.*|external-dns.*|kong.*"} > 0
```

**Comment by piontec** [comment]
OK, cert-manager moved to hydra, updated changelog.

**Pull request merged**
