### PR TITLE
update grafana analytics recording rule

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/roadmap/issues/383

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Review by QuentinBisson — COMMENTED** [review]
Why is there only a changelog change here ?

**Comment by TheoBrigitte** [comment]
Oops cause the other commit went to master somehow, my bad. https://github.com/giantswarm/prometheus-rules/commit/eef0d16e19947c862a47df9f92d39ea340af185f

**Comment by QuentinBisson** [comment]
You might need to allow the grafana metrics to be sent with remove write if it's not done yet https://github.com/giantswarm/prometheus-meta-operator/blob/a01d6ea3e059076d0598144bf047dc1ebe137925/service/controller/resource/monitoring/prometheus/resource.go#L285

**Comment by TheoBrigitte** [comment]
I don't think I need this.

**Pull request merged**
