### PR TITLE
Outside of BH for AzureServicePrincipalExpiresInX

### PR DESCRIPTION
**Pull request by T-Kukawka**

### CODE REVIEW

**Comment by T-Kukawka** [comment]
FYI @anvddriesch @AverageMarcus that was missing  here

**Review by mcbenjemaa — COMMENTED** [review]
@T-Kukawka  please update the changelog

**Comment by T-Kukawka** [comment]
updated @mcbenjemaa

**Review by mcbenjemaa — APPROVED** [review]
LGTM

**Pull request merged**
