### PR TITLE
Removes NodeExporterMissing alert

### PR DESCRIPTION
**Pull request by JosephSalisbury**
This PR:

- removes NodeExporterMissing alert

From https://gigantic.slack.com/archives/C01176DKNP4/p1624874043344900?thread_ts=1624872951.343900&cid=C01176DKNP4, it looks like this alert has been broken for a while. Is anyone actively using it? Otherwise we can just drop it. 

### Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by glitchcrab — APPROVED** [review]
works for me

**Comment by QuentinBisson** [comment]
Did you not work on adding SLO support especially for this ?

**Review by MarcelMue — APPROVED** [review]

**Comment by JosephSalisbury** [comment]
Nah, I didn't know about this alert until @mig4 told me about it :D

**Comment by JosephSalisbury** [comment]
SLO work was to remove `NodeExporterDown`

**Comment by mig4** [comment]
This will look much better now 😉 

alertmanager-dashboard nodeexportermissing pipeline-stable 2021-06-28--14-20-44

**Pull request merged**
