### PR TITLE
Make `NodeExporterDeviceError` only if relevant disk scraping fails.

### PR DESCRIPTION
**Pull request by whites11**
Towards: https://github.com/giantswarm/giantswarm/issues/23451

This PR makes alert less noisy by only checking success of scraping of disks we actually care about

### Checklist

- [x] Update CHANGELOG.md
- [ ] Add [Unit tests](https://github.com/giantswarm/prometheus-rules/#testing)
- [ ] Follow [Alert structure](https://github.com/giantswarm/prometheus-rules/#how-alerts-are-structured)
- [ ] Consider [creating a dashboard](https://docs.giantswarm.io/getting-started/observability/grafana/custom-dashboards/) ([guidelines](https://intranet.giantswarm.io/docs/product/ux/guidelines/dashboards/)) (if it does not exist already) to help oncallers monitor the status of the issue.
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

### CODE REVIEW

**Review by QuantumEnigmaa — APPROVED** [review]
LGTM

**Comment by hervenicol** [comment]
The unit test uses `mountpoint="/usr"`, so it does not generate an alert any more, and fails.
Proves that your filter works BTW :grin:

**Comment by whites11** [comment]
> The unit test uses `mountpoint="/usr"`, so it does not generate an alert any more, and fails. Proves that your filter works BTW grin

yes saw that, thank you for heads up

**Comment by whites11** [comment]
@hervenicol ok to merge for you?

**Review by hervenicol — APPROVED** [review]

**Pull request merged**
