### PR TITLE
Use rate on sum to avoid issues when resetting

### PR DESCRIPTION
**Pull request by paurosello**
This PR:

Change from sun of requests to rate of requests 

Related to https://github.com/giantswarm/giantswarm/issues/22134

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).
- [ ] Alerting rules must have a comment documenting why it needs to exist.
- [ ] Consider creating a dashboard (if it does not exist already) to help oncallers monitor the status of the issue.

### CODE REVIEW

**Comment by paurosello** [comment]
The problem is I don't know how to test this :(

**Review by whites11 — APPROVED** [review]
At a glance it makes sense, but I know SLO alerts calculate a rate on their own so it's important Atlas reviews this as well

**Comment by hervenicol** [comment]
:exclamation: Changing a (broken) counter to a gauge is a breaking change for anything which relies on these metrics.

You can't sum counters in a reliable way, that's a known problem with Prometheus, so I think you're doing right there. :+1: 

Just, maybe give the metrics a new name? Downside is that may create some unused metrics, and use space for nothing.
But do we have a reliable way to know which metrics are used and where? Maybe a few greps in the right repos would be enough to be safe on that?

Let my Atlas colleagues who know better than me complete my comment :wink:

**Comment by paurosello** [comment]
> ❗ Changing a (broken) counter to a gauge is a breaking change for anything which relies on these metrics.
> 
> You can't sum counters in a reliable way, that's a known problem with Prometheus, so I think you're doing right there. 👍
> 
> Just, maybe give the metrics a new name? Downside is that may create some unused metrics, and use space for nothing. But do we have a reliable way to know which metrics are used and where? Maybe a few greps in the right repos would be enough to be safe on that?
> 
> Let my Atlas colleagues who know better than me complete my comment 😉

I am only modifying a subset of the records included in `raw_slo_requests`, so I don't think we can't really rename without creating a mess as all the alarms are based on this metric.

**Comment by hervenicol** [comment]
> I am only modifying a subset of the records included in `raw_slo_requests`, so I don't think we can't really rename without creating a mess as all the alarms are based on this metric.

If I understood correctly, this PR changes **counters** (a metric that only increases, and counts the amount "since ever") into **gauges** (a metric that can gives an instant value, and can be totally different from one read to another).

These are totally different metrics, and changing the contents of the metrics without changing its name will still create a mess with all that's based on it IMO.

**Comment by paurosello** [comment]
Reverted as we are not sure if the alerts still work.

@JosephSalisbury do you have an opinion on this? As you are the SLO master... :)

**Comment by JosephSalisbury** [comment]
@paurosello i'd have to pair with you on this to get into context, feel free to drop an hour in my calendar sometime and we can smash it out <3

**Pull request merged**
