### PR TITLE
Restrict grafana-agent-rules CNP

### PR DESCRIPTION
**Pull request by marieroque**
Towards: https://github.com/giantswarm/giantswarm/issues/30870

This PR overrides the egress rules in the `grafana-agent-rules` CNP to make it more restrictive.

### Checklist

- [x] Update CHANGELOG.md
- [ ] Add [Unit tests](https://github.com/giantswarm/prometheus-rules/#testing)
- [ ] Follow [Alert structure](https://github.com/giantswarm/prometheus-rules/#how-alerts-are-structured)
- [ ] Consider [creating a dashboard](https://docs.giantswarm.io/getting-started/observability/grafana/custom-dashboards/) ([guidelines](https://intranet.giantswarm.io/docs/product/ux/guidelines/dashboards/)) (if it does not exist already) to help oncallers monitor the status of the issue.
- [ ] Request review from oncall area, as well as team (e.g: `oncall-kaas-cloud` GitHub group).

### CODE REVIEW

**Comment by marieroque** [comment]
✅ Tested on `golem` (Mimir installation)

With the new restrictive CNP, communication between components are fine
image

**Comment by QuentinBisson** [comment]
Did you also test it on the observability bundle to make sure it has no issues?

**Review by QuentinBisson — APPROVED** [review]
Apart from my comment all good

**Comment by QuentinBisson** [comment]
Nevermind, i'm dumb

**Pull request merged**
